<?php
print "<h2>";
printf(_("Contacts"));
print "</h2>";
print "<ul>";
print "<li>";
printf(_("Chartroom Jabber/XMPP: \"open-udc@muc.jappix.com\"."));
print "</li>";
print "<li>";
printf(_("Mailing list \"openudc AT googlegroups DOT com\" <a href=\"https://groups.google.com/forum/#!forum/openudc\">https://groups.google.com/forum/#!forum/openudc</a>."));
print "</li>";
print "</ul>";
print "<h3>";
printf(_("Chat-room how-to"));
print "</h3>";
print "<p>";
printf(_("Join the chat-room at \"open-udc@muc.jappix.com\"."));
print "</p>";
print "<p>";
printf(_("You can easily create an XMPP account on <a href=\"https://jappix.com\">https://jappix.com</a> or on any over XMPP provider: <a href=\"http://xmpp.net\">http://xmpp.net</a>."));
print "</p>";
print "<p>";
printf(_("After you can:"));
print "</p>";
print "<ul>";
print "<li>";
printf(_("clicking on Discussion in the bottom right hand corner of the OpenUDC web site;"));
print "</li>";
print "<li>";
printf(_("using the Jabber compatible web-client Jappix;"));
print "</li>";
print "<li>";
printf(_("using MiniJappix on your own site;"));
print "</li>";
print "<li>";
printf(_("install and use a free XMPP client (probably the best way)."));
print "</li>";
print "</ul>";
print "<p>";
printf(_("Recommended XMPP clients: <a href=\"http://gajim.org/\">Gajim</a>, <a href=\"http://psi-plus.com/\">PSI+</a>."));
print "</p>";
?>
